### PR TITLE
Fix CI and Windows install

### PR DESCRIPTION
**Pull request by jdeschamps**
https://github.com/pydev-guide/pyrepo-copier/pull/1 did not pass the CI (particularly on Ubuntu which is annoying)

Added the following defaults in the hope of fixing the CI:
- mode
- github name

### CODE REVIEW

**Comment by jdeschamps** [comment]
The remaining windows errors are probably due to an unknown character:

```bash
l=test@example.com -d project_name=some-projectmple.com
Traceback (most recent call last):
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\joran.deschamps\.conda\envs\copier\Scripts\copier.exe\__main__.py", line 7, in <module>
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\plumbum\cli\application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\plumbum\cli\application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\cli.py", line 68, in _wrapper
    return method(*args, **kwargs)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\cli.py", line 291, in main
    self.parent._worker(
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\main.py", line 707, in run_copy
    src_abspath = self.template_copy_root
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\main.py", line 680, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\template.py", line 423, in subdirectory
    return self.config_data.get("subdirectory", "")
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\template.py", line 279, in config_data
    result = filter_config(self._raw_config)[0]
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\template.py", line 244, in _raw_config
    return load_template_config(conf_paths[0])
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\copier\template.py", line 101, in load_template_config
    flattened_result = lflatten(yaml.load_all(f, Loader=_Loader))
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\funcy\seqs.py", line 193, in lflatten
    return list(flatten(seq, follow))
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\funcy\seqs.py", line 184, in flatten
    for item in seq:
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\yaml\__init__.py", line 90, in load_all
    loader = Loader(stream)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\yaml\loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\joran.deschamps\.conda\envs\copier\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 751: character maps to <undefined>

```

**Comment by jdeschamps** [comment]
Sorry didn't have time to continue investigating.

Note that now this has diverged from the other PR. I'll try to sort out the mess if I get to the bottom of that.

**Comment by jdeschamps** [comment]
Found the trouble maker 🎉 

It now runs on Windows.

@tlambert03 If you are happy with the defaults (https://github.com/pydev-guide/pyrepo-copier/pull/2/commits/ec32639f92e0b9a6315f102a895d7b99b886f798), we can just merge it in!

**Review by tlambert03 — APPROVED** [review]
awesome, thanks!!

**Pull request merged**
