### PR TITLE
Some updates to pyproject.toml formatting and ruff rules

### PR DESCRIPTION
**Pull request by tlambert03**
mostly formatting, but also adds:

- https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch - something I think is almost always good to have
- https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid - commented out... slightly opinionated, but something I always enable

### CODE REVIEW

**Comment by jdeschamps** [comment]
Sounds good, love the type checking!

Why deactivate tidy-import by default?

**Comment by tlambert03** [comment]
Oh I don't know 😂 I guess hesitant to be too draconian since that one is more opinionated by banning deep relative imports.  But I guess there's plenty of opinion in here already.  Would you just enable it?

**Comment by jdeschamps** [comment]
It's tough to define the threshold for "too opinionated". 😄 

But the rule is autofixable and should not make non-specialists tear their hair out, so I'd have a tendency to include it.

**Review by jdeschamps — APPROVED** [review]

**Comment by tlambert03** [comment]
did it :)

**Comment by jdeschamps** [comment]
Cool!

One note: in `pyproject.toml`, there is a typo: `use_precommit` should be `use_pre_commit`!

**Pull request merged**
